wwo_weather_code = {
    "0": "Clear",
    "1": "Mostly clear",
    "2": "Partly cloudy",
    "3": "Overcast",
    "45": "Fog",
    "48": "Depositing Rime Fog",
    "51": "Light drizzle",
    "53": "Moderate drizzle",
    "55": "Dense drizzle",
    "56": "Light freezing drizzle",
    "57": "Dense freezing drizzle",
    "61": "Slight rain",
    "63": "Moderate rain",
    "65": "Heavy rain",
    "66": "Light freezing rain",
    "67": "Heavy freezing rain",
    "71": "Slight snow fall",
    "73": "Moderate snow fall",
    "75": "Heavy snow fall",
    "77": "Snow grains",
    "80": "Slight rain shower",
    "81": "Moderate rain shower",
    "82": "Violent rain shower",
    "85": "Slight snow shower",
    "86": "Heavy snow shower",
    "95": "Thunderstorm",
    "96": "Thunderstorm",
    "99": "Thunderstorm",
}